[build]
  command = "npm run build"
  publish = "dist"

# Gestion du routage SPA (pour React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Proxy pour l'API
[[redirects]]
  from = "/api/*"
  to = "https://blub-trading-board.onrender.com/api/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }

[[redirects]]
  from = "/auth/*"
  to = "https://blub-trading-board.onrender.com/auth/:splat"
  status = 200
  force = true
  headers = { X-From = "Netlify" }